package com.wzn.dao;

import com.wzn.pojo.Product;
import com.wzn.pojo.Product;
import io.lettuce.core.dynamic.annotation.Param;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Set;

@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    /*更新商品*/
    int updateProductKeySelective(Product product);

    /*按照productId或productName 查询*/
    List<Product> findProductByProductIdAndProductName(@Param("productId") Integer productId,
                                                       @Param("productName") String productName);


    /*前台-搜索商品*/
    List<Product> searchProduct(@Param("integerSet") Set<Integer> integerSet,@Param("keyword") String keyword);

}