package com.wzn.dao;

import com.wzn.pojo.Shopping;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ShoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    int insert(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    Shopping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    List<Shopping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shopping record);

    /*
    * 删除地址根据用户
    * */

    int deleteByUserIdShoppingId(@Param("userId") Integer userId,@Param("shoppingId") Integer shoppingId);

    /*更新*/

    int updateBySelectiveKey(Shopping shopping);
}