package com.wzn.dao;

import com.wzn.pojo.Shopping;
import java.util.List;

public interface ShoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    int insert(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    Shopping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    List<Shopping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_shopping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shopping record);
}